"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's^ct^#zrybbl)*5eel*#c_plq5*=pf8!i+^=&73!@s8+44onj8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# Ключи
SIGNATURE_GOVERNMENT_PUBLIC = b'-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArvxBommBLmdzfMY4f2+D\nacq31YB0AvCtCB/KYKXsG73hv/V55RBmr+xPhv1TJz8VY73awtQtCotnDRO3Wejv\nINwvCb1TLXnuoLn4xPqa/v04FxznZGF2MH+DQigEDa+KROhI7SXpQ/Ge3gtcTzop\n1gTxkmHAtlMOBEvPmPffRfxAGUUAJ0W/RGLE+Bi3ynhI0877Q1NJFQUZtrhcjcoO\nu6sHa4kZDaN1Uo62QZskAt6jOBaPRuziYbtw7wAUCdJWoq4H8eYE8wNkFJcj5mfO\nWokHaBNoCh57KC8EaF+oy2ONBapVBEdQIErbo75cWXLmpooyy0bofpobC0ijhPXF\ntQIDAQAB\n-----END PUBLIC KEY-----'
SIGNATURE_GOVERNMENT_PRIVATE = b'-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEArvxBommBLmdzfMY4f2+Dacq31YB0AvCtCB/KYKXsG73hv/V5\n5RBmr+xPhv1TJz8VY73awtQtCotnDRO3WejvINwvCb1TLXnuoLn4xPqa/v04Fxzn\nZGF2MH+DQigEDa+KROhI7SXpQ/Ge3gtcTzop1gTxkmHAtlMOBEvPmPffRfxAGUUA\nJ0W/RGLE+Bi3ynhI0877Q1NJFQUZtrhcjcoOu6sHa4kZDaN1Uo62QZskAt6jOBaP\nRuziYbtw7wAUCdJWoq4H8eYE8wNkFJcj5mfOWokHaBNoCh57KC8EaF+oy2ONBapV\nBEdQIErbo75cWXLmpooyy0bofpobC0ijhPXFtQIDAQABAoIBAQCiq9VkY8p41ilR\nfIC3T3aOWasuqryuowlofQ1JbdYiMBJ2voC0Btw/fWKtLkEoQgfjcnK1HkRFAjUp\nvgN8bQQouyhrWHrD0w+YkWqHzCVdGRAUxIUEF2qlSVU/oi2qf17+EicBd3Xz+OHk\nsBD/giW0VWIx3/gkRu/H5KY4IW6KApyKImOJYpPKY8PTXAooUJCgtrUoOu3fMYwZ\nfByeIPpx/ExUzSKj9mEI3jT5SszwIZYuZMWWUGmP9UkSyxjPFagYAqmpM4zv6uHK\nrffTk5Ufz+VXfs+dHEYmMm3n5ht9Xvywz3tnY5mImmxqOcPukE/BafAs5NAHvivB\nJDG52hBBAoGBAMGXaA5WbUzqPXlBibjb9ZhkyHvmj1/Y2CFd8iu2RUAyKQZXCkq/\ncJdvnG8Tm1kdbbSVRQvQi5Rv8ZPIiBoMwgYO4AqZzlZX7mGhxZrfzqtRH5EBPY9K\ntkXB6D7wxAwVN4vJ25m9V3HtjSa4375MEOiPojLH+Lgu1DrQat3sQSzRAoGBAOdl\nV0ivw3haQb3bW/luD1oRIf7FstrtV6BeFaCF2BxqQmyTl5HoORb5/RCg8VmGgXT2\nR9wZ0zsTkoVK7Gu/6njITMMPb9DpiDWxPzgdu2ihh1Md5wx6OkfnFCRzEu+LrRuI\nugCzg4S2xd7zTmU1L62D5nn7V8gtmA1emFyHMnOlAoGADgHsj40FX5lbVVi+pFeW\nD67LKtvl5+OCz/dCPJN1s01t1n2ZywrLFMoIoajjhrEwbO6YDmDKmLT4396Uqn3d\n1B5ja6DxYyH9p6bS63/iLlcyV4WldKbNRYLgUR2OsekfGchDUX53w1CS9AhQeC58\n0rcB33bEsl8BEDhgYypjFOECgYAxe9OJoMS9dRfAASwPEEFKMoXBlQell8H4coZP\neK/5i6O+0mVEd5PV3QoIR1K1oXUHzS8a2473gD0CMj6S4EzFHZiE0kVIONi/GrN5\nTappOrnUxX1GhtD11W3SSaWQAp+3VqroQXtroyZ3gjKOpCwZAC8GgQCJt25f1Y3h\no6vfXQKBgEHNQzEu8H+oz3GprFuD4yKR5yg0LoYfLoy49VevVJONOB2x7aCUBcYR\nWHvXHsNM5LVNwky9qqAOE4qz6/mE+0fTI09Db9mDT7jNh40upK3MfvVWDyWL0u4u\ntvUYvQSozUt8NY2mX9/9AUt9A2EZG1gn6pcLv4yzgTONOhBBYH4t\n-----END RSA PRIVATE KEY-----'

SIGNATURE_ELECTION_PUBLIC = b'-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuMpRat4j7WY3NoG7Z4sl\nDj+SPOLzY05lsCBUgyKA56+ObztFHgtaUGu9wWAcNauUr164DaMlW4X6yxFemvz1\n6A5tGPSLJCuH3avGu6cvX3n1BklrqcS/SCRDVfMlWj5vEpFAHKF5F+l06kI2bEfm\nxjFqJ+tkOAULVrN56n9OIOidZb7yd5mN30FyCCp08nsjLnLg13ke5lPK3sbMfGhu\nuctjzw2CfoQ3M25W0oUC8kRQAAqKuX4IO/UUkvs6q4ZvTS+FUPKDW2TWnFOQIRB8\n9dCbbxgj1885zr2NewLElJtQ7pGiyme8Ie9DCs/zqFynMqGxnTIdevUTO48N6+0F\nJQIDAQAB\n-----END PUBLIC KEY-----'