# Generated by Django 3.0 on 2019-12-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название голосования')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание голосования')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала голосования')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания голосования')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Candidate')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'голосования',
                'unique_together': {('name', 'start_date', 'end_date')},
            },
        ),
    ]
