# Generated by Django 3.0 on 2019-12-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20191213_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Candidate'),
        ),
    ]
