# Generated by Django 3.0 on 2019-12-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_remove_election_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('passport_series', models.IntegerField(verbose_name='Серия паспорта голосующего')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта голосующего')),
                ('signature_public_key', models.BinaryField(verbose_name='Публичный ключ личной ЭЦП')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Election', verbose_name='Голосование')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='election.Voter', verbose_name='Голосующий')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='election.Voter', verbose_name='Голосующий')),
            ],
        ),
    ]
