# Generated by Django 3.0 on 2019-12-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20191213_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Контракт голосующих', 'verbose_name_plural': 'контракты голосующих'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'Голосующий', 'verbose_name_plural': 'голосующие'},
        ),
        migrations.AddField(
            model_name='contract',
            name='masked_check_public_key',
            field=models.BinaryField(default=b'2', max_length=2048, verbose_name='Ключ шифрования для проверки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='masked_vote_private_key',
            field=models.BinaryField(default=b'2', max_length=2048, verbose_name='Ключ дешифрования для голосования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_election',
            field=models.BinaryField(default=b'2', max_length=2048, verbose_name='Подпись избиркома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_voter',
            field=models.BinaryField(default=b'w', max_length=2048, verbose_name='Подпись голосующего'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_masked_vote_private_key',
            field=models.BinaryField(default=b'2', max_length=2048, verbose_name='Ключ дешифрования для голосования, подписанный избиркомом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter', to='election.Contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter', to='election.Vote', verbose_name='Голос'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('passport_series', 'passport_number', 'election')},
        ),
    ]
