# Generated by Django 3.0 on 2019-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20191213_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='info',
            field=models.TextField(default=122, max_length=256, verbose_name='Информация о голосующем'),
            preserve_default=False,
        ),
    ]
