# Generated by Django 3.0 on 2019-12-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_contract_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='election.Voter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('passport_series', 'passport_number')},
        ),
        migrations.RemoveField(
            model_name='voter',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='election',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote',
        ),
    ]
