# Generated by Django 3.0 on 2019-12-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20191220_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='election',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='voter',
        ),
        migrations.AddField(
            model_name='voter',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='election.Contract'),
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Election'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('passport_series', 'passport_number', 'election')},
        ),
    ]
