# Generated by Django 3.0 on 2019-12-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_auto_20191220_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='election.Contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Election', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='Имя голосующего'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=32, verbose_name='Фамилия голосующего'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='patronymic',
            field=models.CharField(max_length=32, verbose_name='Отчество голосующего'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='signature_public_key',
            field=models.BinaryField(verbose_name='Публичный ключ личной ЭЦП голосующего'),
        ),
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_info_crypted', models.BinaryField(verbose_name='Зашифрованные данные для проверки')),
                ('v', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='election.Vote')),
            ],
            options={
                'verbose_name': 'Проверочная информация',
                'verbose_name_plural': 'проверочные информации',
            },
        ),
    ]
