# Generated by Django 3.0 on 2019-12-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0015_auto_20191220_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinfo',
            name='v',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_info', to='election.Vote'),
        ),
    ]
