# Generated by Django 3.0 on 2019-12-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0016_auto_20191220_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверка закончена?'),
        ),
        migrations.AddField(
            model_name='election',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Голосование закончено?'),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Голос проверен?'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Описание выборов'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания выборов'),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название выборов'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала выборов'),
        ),
    ]
