# Generated by Django 3.0 on 2019-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0017_auto_20191220_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate_signed',
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate_crypted',
            field=models.BinaryField(default=b'12221', verbose_name='candidate, защифрованный голосующим'),
            preserve_default=False,
        ),
    ]
