# Generated by Django 3.0 on 2019-12-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_auto_20191220_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_private_key_masked_signed',
            field=models.BinaryField(default=b'', verbose_name='Ключ дешифрования(закрытый) для голосования, замаскированный секретным множителем избирателя, подписанный избиркомом'),
            preserve_default=False,
        ),
    ]
