# Generated by Django 3.0 on 2019-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_voter_vote_private_key_masked_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_private_key_masked_signed',
            field=models.BinaryField(null=True, verbose_name='Ключ дешифрования(закрытый) для голосования, замаскированный секретным множителем избирателя, подписанный избиркомом'),
        ),
    ]
