# Generated by Django 3.0 on 2019-12-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0020_auto_20191220_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_checked',
            field=models.BooleanField(null=True, verbose_name='Голос проверен?'),
        ),
    ]
