# Generated by Django 3.0 on 2019-12-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0021_auto_20191220_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='election.Voter'),
        ),
    ]
