export const LOGIN_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';


export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';