export const LOGIN_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';


export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const SET_ELECTION_ID = 'SET_ELECTION_ID';
export const SET_K1_DATA = 'SET_K1_DATA';
export const SET_CHECK_AND_VOTE_KEYS = 'SET_CHECK_AND_VOTE_KEYS';
export const SET_M_VOTE = 'SET_M_VOTE';
export const SET_M_CHECK = 'SET_M_CHECK';
export const SET_E_PRIVATE = 'SET_E_PRIVATE';
export const SET_CONTRACT = 'SET_CONTRACT';
export const SET_VOTER_ID = 'SET_VOTER_ID';
export const SET_VOTER_PRIVATE_KEY_SIGNED = 'SET_VOTER_PRIVATE_KEY_SIGNED';