# Generated by Django 3.0 on 2019-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес прописки')),
                ('passport_series', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
                ('signature_public_key', models.IntegerField(verbose_name='Публичный ключ личной ЭЦП')),
                ('signature_i', models.IntegerField(verbose_name='Государственная подпись, удостоверяющая верность данных')),
            ],
        ),
    ]
