# Generated by Django 3.0 on 2019-12-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Гражданин РФ', 'verbose_name_plural': 'Граждане РФ'},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('passport_series', 'passport_number')},
        ),
    ]
