# Generated by Django 3.0 on 2019-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191208_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='signature_i',
            field=models.CharField(max_length=2048, verbose_name='Государственная подпись, удостоверяющая верность данных'),
        ),
        migrations.AlterField(
            model_name='person',
            name='signature_public_key',
            field=models.BinaryField(verbose_name='Публичный ключ личной ЭЦП'),
        ),
    ]
